### ISSUE TITLE
Additional "Run/Debug Configuration" parameters

### ISSUE THREAD

**Issue by sbrunov** [consulo/consulo-nodejs#3]
Hello!

Currently there is only one "Run/Debug Configuration" parameter available — "Script".
The suggestion is to introduce the following parameters:
* Script parameters.
* node.js parameters.
* Working directory.
* Environment variables.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Hi. I fixed this issue. But old configuration will became broken, you need delete - and add new

Thanks

**Comment by sbrunov** [comment]
@VISTALL, great!
Have just checked a part of the functionality of the updated version: the node.js parameters and script parameters are supported.

Best regards,
Sergey Brunov.
