### ISSUE TITLE
Resolving node.js global objects

### ISSUE THREAD

**Issue by sbrunov** [consulo/consulo-nodejs#4]
Hello!

Currently, it seems the node.js plugin can not resolve the node.js global objects. For example, for the `require()` function the IDE shows the warning:

> Unresolved function or method `require()`.

It would be great if the node.js plugin could resolve the node.js global objects.

References:
1. [Node.js Current (v5.1.1), Global Objects](https://nodejs.org/api/globals.html).
2. [Node.js v4.2.3, Global Objects](https://nodejs.org/dist/v4.2.3/docs/api/globals.html).
3. [Node.js v0.12.9, Global Objects](https://nodejs.org/docs/latest-v0.12.x/api/globals.html).
4. [Node.js v0.10.40, Global Objects](https://nodejs.org/docs/latest-v0.10.x/api/globals.html).
5. etc?

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Yeah. I known - its a global problem of JS plugin. Not easy issue - but i am already thinking about it

Ref to https://github.com/consulo/consulo-javascript/issues/12

**Comment by VISTALL** [comment]
Thanks

**Comment by sbrunov** [comment]
@VISTALL, you are welcome!
I am glad that the problem is known.
Thank you for the IDE project!

**Comment by VISTALL** [comment]
Hi - currenly i added initial support for resolving(and added some global stubs).

This is issue fixed. But - next will support Module System https://github.com/consulo/consulo-nodejs/issues/5, and finish global stubs https://github.com/consulo/consulo-nodejs/issues/6

**Comment by VISTALL** [comment]
For correct work you need recreate NodeJS bundle (if u created of course). You will see stub file


![](http://klikr.org/bf019e8df094e7002ff6b30f899d.png)

**Comment by sbrunov** [comment]
Hello, @VISTALL!

Thank you very much for the initial implementation!
Have just checked: the stub definitions are supported.

One interesting moment.
When both «JavaScript (Client)» and «NodeJS» extensions are enabled for the project in the «Modules» tab, the stub definitions are «ignored» (i.e. unresolved).

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Client javascript will confict with NodeJS. its my draft version - later i think will rework it

**Comment by sbrunov** [comment]
Great!
Shall we create the appropriate issue just not to forget?

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
I created it https://github.com/consulo/consulo-javascript/issues/16

Always forgot to report issue - writing code in one person is bad :X

**Comment by sbrunov** [comment]
@VISTALL, thank you!

Best regards,
Sergey Brunov.
