### ISSUE TITLE
Mocha test framework: support for unit-testing

### ISSUE THREAD

**Issue by sbrunov** [consulo/consulo-nodejs#7]
Hello!

It would be great to have the support for unit-testing using the [Mocha test framework](http://mochajs.org/).
The appropriate unit-testing tool windows should be introduced.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Yeah it will be great, but fir now, I dont have any idea how run and report results to Consulo.

Maybe in this month i will spent some time for it.

Thanks for report

**Comment by VISTALL** [comment]
Hi. I added initial support. Now you can run all tests in project via run configuration (Mocha configuration).

But required enabled Mocha extensions.

Resolving is not fixed

**Comment by sbrunov** [comment]
Hello, @VISTALL!

Thank you very much!

## Context
* Consulo 1.0 #1256.
* JavaScript plugin #1526.
* Node.js plugin #1317.
* Mocha plugin #1317.

## Test results
Have just tried running Mocha unit tests: the implementation works as expected.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Nice. Navigation from test tree i will add later.
