### ISSUE TITLE
«node.js» project type

### ISSUE THREAD

**Issue by sbrunov** [consulo/consulo-nodejs#8]
Hello!

## Context
* Consulo 1.0 #1244.
* NodeJS plugin #1287.

## Feature request
It would be great to have a possibility to select the «node.js» project type when creating a new project.
But, currently, the project type is not available.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Hi. I will think about it.

I have one question. How you undestand my module configuration, and how you setuped NodeJS without help? Very interesting for me

**Comment by sbrunov** [comment]
Hello, @VISTALL!

> How you undestand my module configuration

Sorry, it's not clear. What «configuration» do you mean?

> how you setuped NodeJS without help

First of all, I installed the «NodeJS» plugin. After that I found the appropriate project settings window to enable node.js support — the «Project Structure» window: the «Modules» and «Bundles» tabs. 
As far as I remember, it took about 2 — 10 minutes to configure the first node.js project.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Consulo have different module settings (not like in IDEA, i am only who
known fully how setup projects)

**Comment by sbrunov** [comment]
> VISTALL closed this issue…

Have just tried creating a node.js project after updating the plugin: the project has been created just fine.
@VISTALL, thank you!

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Note: More powerfull project creation - is very minor issue, for now i don't known when (in my plan i will implement it after rework Welcome page), due its global issue affect to all plugins
