### ISSUE TITLE
Debugging node.js project: debugger doesn't stop at breakpoint

### ISSUE THREAD

**Issue by sbrunov** [consulo/consulo-nodejs#9]
Hello!

## Context
* Consulo 1.0 #1249.
* Node.js plugin #1298.

## Problem
The debugger doesn't stop at breakpoint.

### Steps to reproduce

1. Create the following node.js script:
    ```js
    console.log("Hello, World!");
    ```

2. Set the breakpoint at the line.

3. Debug the script (for example, using the `Run => Debug <Configuration name>` menu item or using the appropriate keyboard shortcut).

#### Expected result
The debugger stops at the first line.

#### Actual result
The debugger doesn't stop at the first line.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
fixed by https://github.com/consulo/consulo-javascript/commit/6f91f4b684f841e5f0d3e74dbc55144779020216

**Comment by sbrunov** [comment]
@VISTALL, thank you!

## Context
* Consulo 1.0 #1256.
* JavaScript plugin #1526.
* Node.js plugin #1317.

## Test results
The actual result is the same as the expected result.

Best regards,
Sergey Brunov.
